/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author deoiveij
 */
public class index_FRAME extends javax.swing.JFrame {

    /**
     * Creates new form index_FRAME
     */
    public index_FRAME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_Panel = new javax.swing.JPanel();
        menu_item_1 = new javax.swing.JButton();
        menu_item_2 = new javax.swing.JButton();
        menu_item_4 = new javax.swing.JButton();
        menu_item_3 = new javax.swing.JButton();
        index_Panel = new javax.swing.JPanel();
        label_name = new javax.swing.JLabel();
        label_membership = new javax.swing.JLabel();
        label_something = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 102));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menu_Panel.setBackground(new java.awt.Color(255, 204, 204));

        menu_item_1.setText("Check");

        menu_item_2.setText("Class(es)");

        menu_item_4.setText("--*-----");

        menu_item_3.setText("-*-----");

        javax.swing.GroupLayout menu_PanelLayout = new javax.swing.GroupLayout(menu_Panel);
        menu_Panel.setLayout(menu_PanelLayout);
        menu_PanelLayout.setHorizontalGroup(
            menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(menu_item_1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_item_2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_item_3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(menu_item_4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        menu_PanelLayout.setVerticalGroup(
            menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menu_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu_item_2, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(menu_item_4, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(menu_item_3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(menu_item_1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(menu_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 864, -1));

        index_Panel.setBackground(new java.awt.Color(204, 255, 204));

        label_name.setText("*--------");

        label_membership.setText("----*---");

        label_something.setText("--------*");

        javax.swing.GroupLayout index_PanelLayout = new javax.swing.GroupLayout(index_Panel);
        index_Panel.setLayout(index_PanelLayout);
        index_PanelLayout.setHorizontalGroup(
            index_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(index_PanelLayout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(index_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_something)
                    .addComponent(label_membership)
                    .addComponent(label_name))
                .addContainerGap(636, Short.MAX_VALUE))
        );
        index_PanelLayout.setVerticalGroup(
            index_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(index_PanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(label_name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_membership)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_something)
                .addContainerGap(374, Short.MAX_VALUE))
        );

        getContentPane().add(index_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index_FRAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index_FRAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel index_Panel;
    private javax.swing.JLabel label_membership;
    private javax.swing.JLabel label_name;
    private javax.swing.JLabel label_something;
    private javax.swing.JPanel menu_Panel;
    private javax.swing.JButton menu_item_1;
    private javax.swing.JButton menu_item_2;
    private javax.swing.JButton menu_item_3;
    private javax.swing.JButton menu_item_4;
    // End of variables declaration//GEN-END:variables
}
