

package project;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;







/**
 *
 * @author deoiveij
 */
public class loginFrame extends javax.swing.JFrame {
    
    
    public static final Color backgroundColor = new Color(90, 90, 90);
    private static HomeController controller = new HomeController();
    private static EncryptClass encrypt= new EncryptClass();
    
    protected DateTimer timerThread;
    
    
    
    public loginFrame() {
        
        initComponents();
        
        getContentPane().setBackground(backgroundColor);
        login_Panel.setBackground(backgroundColor);
        register_panel.setBackground(backgroundColor);
        login_Panel.setOpaque(true);
        register_panel.setOpaque(true);
        register_panel.setVisible(false);
        register_password_text.setEchoChar('+');
        register_password_text1.setEchoChar('+');
        
        label_info1.setText("<html>*After the creation of your account, will be verified by a  Club Advisor, only then will be activated.</html>");
        
        gender_Box.addItem("Male");
        gender_Box.addItem("Female");
        
        
        timerThread = new DateTimer(label_Date, label_Time);
        timerThread.start();
    
    }
    
    public void imgInitSetup(){
        
        this.setBackground(backgroundColor);
        ImageIcon logo = new ImageIcon(getClass().getResource("/project/assets/fullGym.png"));
        int scale = 2; 
        int width = logo.getIconWidth();
        int newWidth = width / scale;
        icon_1.setBorderPainted(false);
        icon_1.setBorder(null);
        icon_1.setContentAreaFilled(false);
        icon_1.setFocusPainted(false);
        icon_1.setBackground(new Color(0,0,0));
        icon_1.setIcon(new ImageIcon(logo.getImage().getScaledInstance(newWidth, -1,java.awt.Image.SCALE_SMOOTH)));
        
        
        ImageIcon dateLogo = new ImageIcon(getClass().getResource("/project/assets/date_icon.png"));
        date_label.setIcon(new ImageIcon(dateLogo.getImage().getScaledInstance(60, -1,java.awt.Image.SCALE_SMOOTH)));
        ImageIcon timeLogo = new ImageIcon(getClass().getResource("/project/assets/time_icon.png"));
        hours_label.setIcon(new ImageIcon(timeLogo.getImage().getScaledInstance(60, -1,java.awt.Image.SCALE_SMOOTH)));
        
        
        ImageIcon exitLogo = new ImageIcon(getClass().getResource("/project/assets/exit.png"));
        exit_btn.setIcon(new ImageIcon(exitLogo.getImage().getScaledInstance(60, -1,java.awt.Image.SCALE_SMOOTH)));
        
        ImageIcon backLogo = new ImageIcon(getClass().getResource("/project/assets/back.png"));
        back_btn.setIcon(new ImageIcon(backLogo.getImage().getScaledInstance(60, -1,java.awt.Image.SCALE_SMOOTH)));
        
        
        ImageIcon signUPlogo = new ImageIcon(getClass().getResource("/project/assets/signUP_icon.png"));
        register_btn_action.setBorderPainted(false);
        register_btn_action.setBorder(null);
        register_btn_action.setContentAreaFilled(false);
        register_btn_action.setFocusPainted(false);
        register_btn_action.setBackground(new Color(0,0,0));
        register_btn_action.setIcon(new ImageIcon(signUPlogo.getImage().getScaledInstance(140, -1,java.awt.Image.SCALE_SMOOTH)));
        
        ImageIcon signINlogo = new ImageIcon(getClass().getResource("/project/assets/signIN_icon.png"));
        btn_action.setBorderPainted(false);
        btn_action.setBorder(null);
        btn_action.setContentAreaFilled(false);
        btn_action.setFocusPainted(false);
        btn_action.setBackground(new Color(0,0,0));
        btn_action.setIcon(new ImageIcon(signINlogo.getImage().getScaledInstance(140, -1,java.awt.Image.SCALE_SMOOTH)));
        
        
        ImageIcon click2SignUPLogo = new ImageIcon(getClass().getResource("/project/assets/click2SignUP.png"));
        register_label.setIcon(new ImageIcon(click2SignUPLogo.getImage().getScaledInstance(280, -1,java.awt.Image.SCALE_SMOOTH)));
        ImageIcon label_title_registerLogo = new ImageIcon(getClass().getResource("/project/assets/regisArea.png"));
        label_title_register_panel.setIcon(new ImageIcon(label_title_registerLogo.getImage().getScaledInstance(200, -1,java.awt.Image.SCALE_SMOOTH)));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_Time = new javax.swing.JLabel();
        label_Date = new javax.swing.JLabel();
        date_label = new javax.swing.JLabel();
        hours_label = new javax.swing.JLabel();
        login_Panel = new javax.swing.JPanel();
        username_text_login = new javax.swing.JTextField();
        btn_action = new javax.swing.JButton();
        register_label = new javax.swing.JLabel();
        password_text_login = new javax.swing.JPasswordField();
        labelUser_Login = new javax.swing.JLabel();
        labelPW_Login = new javax.swing.JLabel();
        icon_1 = new javax.swing.JButton();
        save_UserData = new javax.swing.JCheckBox();
        label_info_save = new javax.swing.JLabel();
        register_panel = new javax.swing.JPanel();
        label_title_register_panel = new javax.swing.JLabel();
        register_username_text = new javax.swing.JTextField();
        register_email_text = new javax.swing.JTextField();
        label_username = new javax.swing.JLabel();
        label_password = new javax.swing.JLabel();
        label_mail = new javax.swing.JLabel();
        label_gender = new javax.swing.JLabel();
        back_btn = new javax.swing.JLabel();
        register_btn_action = new javax.swing.JButton();
        register_password_text1 = new javax.swing.JPasswordField();
        register_password_text = new javax.swing.JPasswordField();
        register_address_text = new javax.swing.JTextField();
        label_address = new javax.swing.JLabel();
        gender_Box = new javax.swing.JComboBox<>();
        label_password1 = new javax.swing.JLabel();
        label_info1 = new javax.swing.JLabel();
        exit_btn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(javax.swing.UIManager.getDefaults().getColor("Button.light"));
        setMaximumSize(new java.awt.Dimension(492, 431));
        setMinimumSize(new java.awt.Dimension(492, 431));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(492, 431));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_Time.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        label_Time.setForeground(new java.awt.Color(255, 255, 255));
        label_Time.setText("< h/m/s>");
        getContentPane().add(label_Time, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 120, -1));

        label_Date.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 12)); // NOI18N
        label_Date.setForeground(new java.awt.Color(255, 255, 255));
        label_Date.setText("<yy/mm/dd>");
        getContentPane().add(label_Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 384, 120, 20));

        date_label.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        getContentPane().add(date_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 90, 30));
        getContentPane().add(hours_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 70, 30));

        login_Panel.setMaximumSize(new java.awt.Dimension(250, 300));
        login_Panel.setMinimumSize(new java.awt.Dimension(250, 300));
        login_Panel.setPreferredSize(new java.awt.Dimension(250, 300));

        btn_action.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        btn_action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actionActionPerformed(evt);
            }
        });

        register_label.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        register_label.setToolTipText("Create an account for free!");
        register_label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                register_labelMouseClicked(evt);
            }
        });

        labelUser_Login.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        labelUser_Login.setForeground(new java.awt.Color(255, 255, 255));
        labelUser_Login.setText("Username");

        labelPW_Login.setFont(new java.awt.Font("Consolas", 0, 10)); // NOI18N
        labelPW_Login.setForeground(new java.awt.Color(255, 255, 255));
        labelPW_Login.setText("Password");

        icon_1.setBackground(login_Panel.getBackground());
        icon_1.setBorder(null);

        save_UserData.setContentAreaFilled(false);

        label_info_save.setFont(new java.awt.Font("Consolas", 1, 11)); // NOI18N
        label_info_save.setForeground(new java.awt.Color(255, 255, 255));
        label_info_save.setText("Save session");
        label_info_save.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout login_PanelLayout = new javax.swing.GroupLayout(login_Panel);
        login_Panel.setLayout(login_PanelLayout);
        login_PanelLayout.setHorizontalGroup(
            login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(icon_1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, login_PanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(register_label, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(login_PanelLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(login_PanelLayout.createSequentialGroup()
                        .addComponent(label_info_save)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save_UserData, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(password_text_login, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addComponent(username_text_login, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                        .addComponent(labelUser_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPW_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_action, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        login_PanelLayout.setVerticalGroup(
            login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(login_PanelLayout.createSequentialGroup()
                .addComponent(icon_1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(3, 3, 3)
                .addComponent(labelUser_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_text_login, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPW_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_text_login, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(login_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_info_save, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(save_UserData, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_action)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(register_label, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(login_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 40, 460, 350));

        register_panel.setMaximumSize(new java.awt.Dimension(400, 300));
        register_panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_title_register_panel.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        register_panel.add(label_title_register_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 240, 36));
        register_panel.add(register_username_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 74, 167, 30));
        register_panel.add(register_email_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 167, 30));

        label_username.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_username.setForeground(new java.awt.Color(255, 255, 255));
        label_username.setText("Username");
        register_panel.add(label_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 54, -1, -1));

        label_password.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_password.setForeground(new java.awt.Color(255, 255, 255));
        label_password.setText("Password Again");
        register_panel.add(label_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        label_mail.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_mail.setForeground(new java.awt.Color(255, 255, 255));
        label_mail.setText("Email");
        register_panel.add(label_mail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        label_gender.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_gender.setForeground(new java.awt.Color(255, 255, 255));
        label_gender.setText("Gender");
        register_panel.add(label_gender, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 60, 30));

        back_btn.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        back_btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back_btn.setToolTipText("back to login");
        back_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                back_btnMouseClicked(evt);
            }
        });
        register_panel.add(back_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 60, 30));

        register_btn_action.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btn_actionActionPerformed(evt);
            }
        });
        register_panel.add(register_btn_action, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, 150, 50));
        register_panel.add(register_password_text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 170, 30));
        register_panel.add(register_password_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 170, 30));
        register_panel.add(register_address_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 167, 30));

        label_address.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_address.setForeground(new java.awt.Color(255, 255, 255));
        label_address.setText("Address");
        register_panel.add(label_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, -1, -1));

        register_panel.add(gender_Box, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 100, 30));

        label_password1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_password1.setForeground(new java.awt.Color(255, 255, 255));
        label_password1.setText("Password");
        register_panel.add(label_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        label_info1.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        label_info1.setForeground(new java.awt.Color(255, 51, 0));
        label_info1.setToolTipText("");
        register_panel.add(label_info1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 450, 30));

        getContentPane().add(register_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 450, 360));

        exit_btn.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        exit_btn.setToolTipText("Exit ");
        exit_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit_btnMouseClicked(evt);
            }
        });
        getContentPane().add(exit_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 60, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
    *
    * LOGIN BTN
    */
    private void btn_actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actionActionPerformed
       List<String> dataUSPW = new ArrayList<String>();
       
       
        if(username_text_login.getText().equals("") || password_text_login .getText().equals("")){
            controller.alertERROR("Empty");
            //
            
        }else{
            dataUSPW.add(username_text_login.getText());
            dataUSPW.add(password_text_login.getText());
            dataUSPW.set(1,encrypt.setPassword2Hash(dataUSPW.get(1)));
            if(save_UserData.isSelected()){
                
            }else{
                username_text_login.setText("");
                password_text_login.setText("");
            }
            controller.checkLogin(dataUSPW);
            
            
        };
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_actionActionPerformed

    
    /*Back BTN ACTION*/
    private void back_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_back_btnMouseClicked
        register_panel.setVisible(false);
        login_Panel.setVisible(true);
    }//GEN-LAST:event_back_btnMouseClicked
    
    /*New Client  BTN ACTION*/
    private void register_labelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_register_labelMouseClicked
        login_Panel.setVisible(false);
        register_panel.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_register_labelMouseClicked

    
/**
 *
 * Get data from textbox objects,
 * check if fields are empty
 * check if fields password are equal and more than 8 characters
 * check if email have email parameters
 * set password field with encryption
 * 
 * save it inside array and send back to controller(HomeController->Database),
 * 
 * REGISTER USER BTN ACTION
 */    
    private void register_btn_actionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btn_actionActionPerformed

        
        List<String> data = new ArrayList<String>();
        
        //System.out.println(label_Date.getText());
        //System.out.println(label_Time.getText());
        if(register_username_text.getText().equals("")||register_password_text.getText().equals("")||register_password_text1.getText().equals("")||register_address_text.getText().equals("")||register_email_text.getText().equals("")||gender_Box.getSelectedItem().toString()==""){
        
        controller.alertERROR("Empty Field");
        
        }else{
            //System.out.println(controller.checkUsername(register_username_text.getText().toString()));
            if(controller.checkUsername(register_username_text.getText().toString())>=1){
                    
                    controller.alertERROR("Username "+register_username_text.getText()+" Already in use!");
            }else{
                if(register_password_text.getText().equals(register_password_text1.getText())&& register_password_text.getDocument().getLength()>=8 && register_password_text.getDocument().getLength()<=15){
                        
                        if(register_email_text.getText().toString().indexOf(' ')>=0 ||register_email_text.getText().toString().indexOf('@')<0 || register_email_text.getText().toString().indexOf('.')<0 ){
                       
                        controller.alertERROR("Invalid Email");  
                        }else{
                            data.add(register_username_text.getText().toLowerCase());//0 - username 
                            data.add(register_password_text.getText());//1 - pw
                            data.add(register_email_text.getText());//2 - email
                            data.add(register_address_text.getText());//3 - address
                            data.set(1,encrypt.setPassword2Hash(register_password_text.getText()));//pe encrypt

                            data.add(label_Date.getText().replaceAll("\\s+",""));//4 - today date
                            data.add(String.valueOf(gender_Box.getSelectedItem()));// 
                            //data.add(label_Time.getText());
                        
                            if(controller.registerREQmember(data)==1){
                                controller.alertINFO("Account Created Succesfully");
                                register_username_text.setText("");
                                register_password_text.setText("");
                                register_password_text1.setText("");
                                register_email_text.setText("");
                                register_address_text.setText("");                             
                                register_panel.setVisible(false);
                                login_Panel.setVisible(true);
                                
                            }else{
                                controller.alertERROR("Account Not Created");
                            } 
                        }
                }else{

                controller.alertERROR("<html>Password :<br> field not equal or <br> not at least 8 with max of 15 digits</html>");
                }
            }

        }   // TODO add your handling code here:
    }//GEN-LAST:event_register_btn_actionActionPerformed

    private void exit_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit_btnMouseClicked
        timerThread.exitProcedure();
        // TODO add your handling code here:
    }//GEN-LAST:event_exit_btnMouseClicked

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back_btn;
    private javax.swing.JButton btn_action;
    private javax.swing.JLabel date_label;
    private javax.swing.JLabel exit_btn;
    private javax.swing.JComboBox<String> gender_Box;
    private javax.swing.JLabel hours_label;
    private javax.swing.JButton icon_1;
    private javax.swing.JLabel labelPW_Login;
    private javax.swing.JLabel labelUser_Login;
    private javax.swing.JLabel label_Date;
    private javax.swing.JLabel label_Time;
    private javax.swing.JLabel label_address;
    private javax.swing.JLabel label_gender;
    private javax.swing.JLabel label_info1;
    private javax.swing.JLabel label_info_save;
    private javax.swing.JLabel label_mail;
    private javax.swing.JLabel label_password;
    private javax.swing.JLabel label_password1;
    private javax.swing.JLabel label_title_register_panel;
    private javax.swing.JLabel label_username;
    private javax.swing.JPanel login_Panel;
    private javax.swing.JPasswordField password_text_login;
    private javax.swing.JTextField register_address_text;
    private javax.swing.JButton register_btn_action;
    private javax.swing.JTextField register_email_text;
    private javax.swing.JLabel register_label;
    private javax.swing.JPanel register_panel;
    private javax.swing.JPasswordField register_password_text;
    private javax.swing.JPasswordField register_password_text1;
    private javax.swing.JTextField register_username_text;
    private javax.swing.JCheckBox save_UserData;
    private javax.swing.JTextField username_text_login;
    // End of variables declaration//GEN-END:variables








}
